name: Release app

on:
  # Allows you to run this workflow manually from the Actions tab
  # Workflowの手動起動の設定です。
  # version_numberを入力できるようにしています。
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # 実行環境をmacに設定。
    runs-on: macos-latest

    steps:
      - name: Show Xcode version
        run: xcodebuild -version    
        
      - name: Install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      # defaultでWorkflowを実行したbranchがcheckoutされる。
      - uses: actions/checkout@v2

      - name: Environment
        run: |
          brew install cmake ninja bison flex freetype mingw-w64 gnutls libtiff krb5 FAudio lcms2 gstreamer gst-plugins-base sane-backends libusb libgsm libgphoto2 molten-vk vulkan-headers spirv-cross spirv-tools glslang
          export PATH="/usr/local/opt/net-snmp/sbin:/usr/local/opt/net-snmp/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/krb5/sbin:/usr/local/opt/krb5/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
          export GUILE_LOAD_PATH="/usr/local/share/guile/site/3.0"
          export GUILE_LOAD_COMPILED_PATH="/usr/local/lib/guile/3.0/site-ccache"
          export GUILE_SYSTEM_EXTENSIONS_PATH="/usr/local/lib/guile/3.0/extensions"
          export GUILE_TLS_CERTIFICATE_DIRECTORY=/usr/local/etc/gnutls/
        
      - name: SPIRV-Headers Build
        run: git clone https://github.com/KhronosGroup/SPIRV-Headers.git && cd SPIRV-Headers && mkdir build && cd build && cmake .. && make install && cd ../..
